output "cluster_endpoint" {
  description = "Endpoint for eks_cluster control plane."
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster.kubeconfig
}

output "cluster_id" {
  description = "cluster_id"
  value       = module.eks_cluster.cluster_id
}

