output "cluster_endpoint" {
  description = "Endpoint for eks_cluster control plane."
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster.kubeconfig
}

output "cluster_id" {
  description = "cluster_id"
  value       = module.eks_cluster.cluster_id
}

output "aws_eks_cluster_cluster_certificate_authority_data" {
  description = "aws_eks_cluster_cluster_certificate_authority_data"
  value       = data.aws_eks_cluster.cluster.certificate_authority.0.data
}


output "aws_eks_cluster_auth_cluster_token" {
  description = "aws_eks_cluster_auth_cluster_token"
  value       = data.aws_eks_cluster_auth.cluster.token
}
